### ISSUE TITLE
Training Query

### ISSUE THREAD

**Issue by robynande** [zhenhua-wang/MissingData_DL#2]
Hi,
I've been implementing your code, and its been really simple to work with due to the great structure- thank you!
I have a question about the GAIN_v2.py script, I noticed that you're training the first and third layers of the generator, but all three layers of the discriminator. What was the rationale behind not training this central layer? I couldn't find a reference to it in the paper, but may have missed it.
Thanks! Robyn

**Comment by zhenhua-wang** [comment]
Hey Robyn, thank you for pointing this out! 

That should be a typo. I was testing various structures. I will fix this soon!
